# The module is self-contained when driven by an external orchestrator (e.g.
# ibm/onboarding/cloud-shell-onboard.sh in the parent cloud-connect-deployments
# repo), which reads the outputs and posts them to the Salt Security backend
# itself. In that case leave manual_deploy = false and all other variables
# unset.
#
# When manual_deploy = true the module POSTs the status updates itself from
# inside `terraform apply` — intended for customers who apply from the
# Schematics UI without the orchestrator script. In that mode salt_host,
# salt_auth_token, and attempt_id are required.

variable "manual_deploy" {
  description = "When true, the module POSTs Initiated/Succeeded statuses to the Salt backend itself. Use for Schematics UI-driven applies without the Cloud Shell orchestrator. Default false: an external script owns the backend handoff."
  type        = bool
  default     = false
}

variable "salt_host" {
  description = "Salt Security backend URL (e.g. https://api.salt.security). Required when manual_deploy = true."
  type        = string
  default     = ""
}

variable "salt_auth_token" {
  description = "Bearer token from the Salt dashboard. Required when manual_deploy = true."
  type        = string
  default     = ""
  sensitive   = true
}

variable "attempt_id" {
  description = "Onboarding attempt UUID generated by the Salt backend. Required when manual_deploy = true."
  type        = string
  default     = ""
}

variable "installation_id" {
  description = "Salt tenant/installation UUID. Optional even in manual_deploy mode."
  type        = string
  default     = ""
}