# Required inputs — the module always POSTs Initiated and Succeeded to the
# Salt backend from inside `terraform apply`. The caller supplies the bearer
# token and attempt UUID that come from the Salt dashboard; both the Cloud
# Shell orchestrator (ibm/single_account/ibm-connect-onboard.sh) and the
# Schematics-UI path pass these in as workspace variables.

variable "salt_host" {
  description = "Salt Security backend URL, e.g. https://api.salt.security."
  type        = string
  validation {
    condition     = var.salt_host != ""
    error_message = "salt_host must be set to the Salt backend URL."
  }
}

variable "salt_auth_token" {
  description = "Bearer token from the Salt dashboard."
  type        = string
  sensitive   = true
  validation {
    condition     = var.salt_auth_token != ""
    error_message = "salt_auth_token must be set."
  }
}

variable "attempt_id" {
  description = "Onboarding attempt UUID generated by the Salt backend."
  type        = string
  validation {
    condition     = var.attempt_id != ""
    error_message = "attempt_id must be set to the Salt-generated onboarding UUID."
  }
}

variable "installation_id" {
  description = "Salt tenant/installation UUID. Optional."
  type        = string
  default     = ""
}