variable "salt_host" {
  description = "Salt Security backend host URL (e.g., https://api.salt.security)."
  type        = string

  validation {
    condition     = can(regex("^https?://", var.salt_host))
    error_message = "salt_host must start with http:// or https://."
  }
}

variable "salt_auth_token" {
  description = "Bearer token for the Salt Security backend. Sent in the Authorization header; never stored in outputs."
  type        = string
  sensitive   = true
}

variable "attempt_id" {
  description = "Onboarding attempt ID (UUID) generated by the Salt backend. Used to correlate retries of the same onboarding. Auto-generated if empty, but callers should supply the backend-provided value."
  type        = string
  default     = ""
}