name: Release

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  bump_and_release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: false
          WITH_V: true
          DEFAULT_BUMP: patch
          FORCE_WITHOUT_CHANGES: true

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.bump.outputs.new_tag }}
          name: ${{ steps.bump.outputs.new_tag }}
          generateReleaseNotes: true