name: terraform-ibm-salt-cloud-connect

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  bump:
    uses: Secful/salt-cicd/.github/workflows/bump.yml@master
    permissions:
      id-token: write
      contents: write
    if: github.ref == 'refs/heads/master'
    secrets: inherit